### PR TITLE
Fix Error :  'Resource.Designer.cs' could not be found.

### PR DESCRIPTION
**Pull request by Alibesharat**
When I tried to build project  I faced with this error message :

> Source file 'C:\Users\username\Source\Repos\plugin-template\Feature1\obj\Debug\MonoAndroid81   \Resource.Designer.cs' could not be found.	Feature1 (netstandard1.0)

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Hmmm @onovotny ?

**Comment by jamesmontemagno** [comment]
Might just need latest nuget. i just updated to .43

**Comment by Alibesharat** [comment]
Latest Commit fixed the error

**Comment by jamesmontemagno** [comment]
yay! <3

**Pull request closed without merging**
